### ISSUE TITLE
LEGAL - Open source contract with Jimber & TF AG

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_legal#10]
- [ ] use [template](https://docs.google.com/document/d/1jerMTME79fOLqRRDS1CvzTyIZYxaQ1DbnqVECJbe8w8/edit)
 - [ ] link to repo crystaluniverse
 - [ ] make sure all experiences for digital twin are on crystal universe account (kristof)
- [ ] add that jimber browser can be used for free by TF Foundation

**Comment by Sacha96** [comment]
@despiegk moved previously created story to here. all that is legal should be here

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/74
