### ISSUE TITLE
add new t&c section: TF DMCC t&c

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_legal#13]
- make a new branch called development_dmcc from development
- create new file under /wiki folder, with name terms_conditions_tf_dmcc
- add one new md file called tf_dmcc.md
- fill in the t&c information
- commit and push (make sure youre on the development_dmcc branch still)
- edit the sidebar.md (make sure youre on the development_dmcc branch still)
- add TF DMCC Section, link the md file there
- create a pr to merge to 'development' and assign @sasha-astiadi as a reviewer

**Comment by sasha-astiadi** [comment]
https://github.com/ourworld-tsc/www_ourparadise_new/issues/3

**Comment by despiegk** [comment]
we need to do this in different way, we are working on hero based publiushing for T&C
