### ISSUE TITLE
Broken link to grid users section

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_legal#14]
At the top of the main terms and conditions there is a broken link:

![image](https://github.com/threefoldfoundation/info_legal/assets/17682591/c2ed9d72-3af3-4557-b879-bb3dce542c89)

It seems there are no longer separate files for v2 and v3 users t&c.

**Comment by sasha-astiadi** [comment]
updated https://github.com/threefoldfoundation/info_legal/commit/854c77013d8093f0e3ef9f5bc0ae0ab2d27b954e
