### ISSUE TITLE
LEGAL WIKI - don't we need T&C for users of TFGrid?

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_legal#2]

**Comment by marizawellesleywesley** [comment]
YES, we need a recommended” “Standard” Contract between Farmers and Capacity Users: 
The proposed “Standard”/”Minimum” Contract does not need to be binding, but each farmer or capacity user can instruct their 3Bot whether they contract at the terms of the Standard contract or at separate terms according to a separate, negotiated contract or a specific standard contract published by the farmer.
Creating such a “recommended” Standard Contract will protect and serve the entire farmer community, regardless of their size and know how, and protect the many farmers who will not be able to afford sophisticated legal advice. it will also protect TF Foundation, the TF Grid and the TF Tech. It will create a safe environment and will create a stable, democratic environment – extremely beneficial to the intended large farmer community 
This Standard Contract would include minimum standard terms appropriate for the level of service contracted for (uptime, computing units., network units etc). It would exclude liability of the farmers, the duration of the services only as contracted for (time period indicated in the 3Bot system; accordingly there is no “term” or “notice period of termination” there will be pricing regimes for different times/levels/ etc as contracted for via the 3Bot and the instructions given by the parties to the 3Bots. One should create these drawing on appropriate industry agreement (like the AWS agreement) and review and submit to outside counsel – for liability reasons these contracts need to be vetted by experts.

**Comment by Vilnite** [comment]
Please let's see this with Pierre.

**Comment by VonSub** [comment]
@vanhoorp has created this a while ago already I believe. 
I talked to him and he would check if it was sufficient for those with access: https://github.com/threefoldfoundation/info_legal/blob/master/src/terms_conditions_griduser.md
