### ISSUE TITLE
LEGAL WIKI - cultivation should not be described like this

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_legal#3]
![image](https://user-images.githubusercontent.com/6021844/92354064-e5af4c00-f0e1-11ea-9f9d-75652ba03212.png)

TFT can be charged for any possible service on the grid

**Comment by despiegk** [comment]
where did this text came from?
was not optimal

**Comment by despiegk** [comment]
needs to be in line with new farming

**Comment by VonSub** [comment]
@vanhoorp will also look into this one as agreed on in a call we had last tuesday.

**Comment by Vilnite** [comment]
See on circles tool: https://circles.threefold.me/project/despiegk-product_web_threefold/issue/49
